"""agents.txt + workflow + badge template generators.

Mirrors bin/lib/template.js exactly so the Node and Python CLIs produce
byte-identical files for identical inputs.
"""
from __future__ import annotations

from datetime import date


def build_agents_txt(
    *,
    project: str,
    maintainer: str,
    contact_for_agents: str | None,
    ai_disclosure_required: bool,
    allow_prs_without_approval: bool,
    protect_sensitive_paths: bool,
    repo_type: str,
) -> str:
    today = date.today().isoformat()

    base_allowed = [
        "read_documentation",
        "read_source_code",
        "run_tests_in_ci",
        "comment_on_issue",
        "propose_design",
    ]
    if allow_prs_without_approval:
        base_allowed.insert(2, "file_pull_request")

    base_prohibited = [
        "merge_to_main",
        "deploy_to_production",
        "modify_secrets",
        "exfiltrate_secrets",
        "bypass_2fa",
        "bypass_captcha",
        "deceptive_tracking",
        "spam",
        "impersonation",
    ]
    if repo_type.startswith("node"):
        base_prohibited.append("publish_to_npm")
    if repo_type.startswith("python"):
        base_prohibited.append("publish_to_pypi")

    approvals = [
        "schema_migrations",
        "production_deploys",
        "dependency_upgrades_major",
        "new_external_service_integrations",
    ]
    sensitive_globs = (
        "payments/**, billing/**, auth/**, security/**, secrets/**"
        if protect_sensitive_paths
        else None
    )

    entry_points = ["agent_guide = /AGENTS.md"]
    if repo_type.startswith("node"):
        entry_points.append("test_command = npm test")
        entry_points.append("lint_command = npm run lint")
    elif repo_type.startswith("python"):
        entry_points.append("test_command = python3 -m pytest -q")
    elif repo_type.startswith("go"):
        entry_points.append("test_command = go test ./...")
    elif repo_type.startswith("rust"):
        entry_points.append("test_command = cargo test")

    lines: list[str] = []
    lines.append("# agents.txt v1.0")
    lines.append("# https://github.com/barneywohl/agentpress")
    lines.append("#")
    lines.append("# This file declares what autonomous AI agents are allowed and expected to do")
    lines.append("# in this repository. Generated by AgentPress; tailor as needed.")
    lines.append("")
    lines.append("[meta]")
    lines.append("spec_version = 1.0")
    lines.append(f"project = {project}")
    lines.append(f"maintainer = {maintainer or 'maintainer@example.com'}")
    if contact_for_agents:
        lines.append(f"contact_for_agents = {contact_for_agents}")
    lines.append(f"last_updated = {today}")
    lines.append(f"ai_disclosure_required = {'true' if ai_disclosure_required else 'false'}")
    lines.append("")
    lines.append("[allowed_actions]")
    lines.extend(base_allowed)
    lines.append("")
    lines.append("[prohibited_actions]")
    lines.extend(base_prohibited)
    lines.append("")
    lines.append("[requires_human_approval]")
    lines.extend(approvals)
    if sensitive_globs:
        lines.append(f"changes_touching = {sensitive_globs}")
    lines.append("")
    lines.append("[entry_points]")
    lines.extend(entry_points)
    lines.append("")
    lines.append("[rate_limits]")
    lines.append("max_pull_requests_per_day = 5")
    lines.append("max_issues_per_day = 10")
    lines.append("max_comments_per_day = 25")
    lines.append("")
    lines.append("[scope]")
    lines.append("max_files_changed = 25")
    lines.append("max_lines_changed = 800")
    lines.append("single_purpose_pr = true")
    lines.append("")
    lines.append("[disclosure]")
    lines.append("pr_label = agent-authored")
    lines.append("commit_trailer = Authored-by-Agent: <agent-name> <agent-version>")
    lines.append(f"require_attribution_in_pr_body = {'true' if ai_disclosure_required else 'false'}")
    lines.append("")
    return "\n".join(lines) + "\n"


def build_github_workflow() -> str:
    return """name: agents.txt validate

on:
  pull_request:
    paths: ['agents.txt']
  push:
    branches: [main]
    paths: ['agents.txt']

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: barneywohl/agentpress/actions/setup-action@v1
        with:
          file: agents.txt
          fail-on-warnings: false
"""


def build_badge_snippet(origin: dict | None = None) -> str:
    return (
        "[![agents.txt](https://img.shields.io/badge/agents.txt-v1.0-2563eb"
        "?style=flat-square&logo=githubactions&logoColor=white)]"
        "(https://github.com/barneywohl/agentpress)"
    )
