#!/usr/bin/env bash
set -euo pipefail

# Generated by scripts/agentpress_gorilla_manifest_acceptance_harness.py
# Local-only replay helper: runs only commands that passed the manifest safety allowlist.
# Jake explicit approval remains required before any public push/publish/deploy, outreach, wallet, payment, or external-send action.
# Harness ID: wave96-gorilla-manifest-acceptance-7245fbf9e8bd

echo 'AgentPress Gorilla manifest acceptance replay (local-only)'
echo 'Stop before any public action; Jake approval required.'

echo 'inspect step 1: inspect_receipt'
echo 'running step 2: run_first_useful_command'
python3 scripts/agentpress.py gorilla-utility-pack --out agentpress/gorilla/utility-pack --json

echo 'running step 3: capture_proof'
python3 scripts/agentpress.py proof-capture --task-id glm-gorilla-bootstrap-conveyor --evidence-dir agentpress/gorilla/glm-bootstrap-conveyor-wave87-proof --artifacts agentpress/gorilla/glm-bootstrap-conveyor-wave87.json --commands 'python3 scripts/agentpress.py gorilla-utility-pack --out agentpress/gorilla/utility-pack --json' --json

echo 'Replay complete; local commands run: 2'
